/**
 * India - País 34
 */

import { Country } from './types';

export const india: Country = {
  id: 'india',
  name: 'India',
  region: 'Asia',
  flag: '🇮🇳',
  coordinates: { latitude: 20.5937, longitude: 78.9629 },
  description: 'Mayor diáspora del mundo. Potencia tecnológica y cultural.',
  culturalFacts: [
    'Taj Mahal, maravilla del mundo',
    'Bollywood, mayor industria del cine',
    'Yoga y meditación',
    'Más de 700 lenguas habladas',
  ],
  migrationContext: {
    reasons: ['Oportunidades en tecnología', 'Educación superior', 'Movilidad profesional', 'Reunificación'],
    challenges: ['Brain drain', 'Discriminación', 'Visas restrictivas', 'Estereotipos'],
    destinations: ['Emiratos Árabes', 'Estados Unidos', 'Reino Unido', 'Canadá', 'Australia'],
    statistics: { emigrants: '18 millones (mayor diáspora)', remittances: '$87 mil millones USD (mayor receptor)' },
  },
  activities: [
    {
      id: 'india_trivia',
      type: 'trivia',
      title: 'India Milenaria',
      description: 'Descubre India',
      difficulty: 'hard',
      questions: [
        {
          question: '¿Qué país tiene la mayor diáspora del mundo?',
          options: ['China', 'India', 'México', 'Filipinas'],
          correctAnswer: 1,
          explanation: 'India tiene 18 millones de personas en el exterior, la mayor diáspora del mundo, viviendo principalmente en Emiratos Árabes y Estados Unidos.',
          difficulty: 'hard',
        },
        {
          question: '¿Qué país recibe más remesas del mundo?',
          options: ['México', 'Filipinas', 'India', 'China'],
          correctAnswer: 2,
          explanation: 'India recibe $87 mil millones USD anuales en remesas, el mayor receptor mundial, representando el 3% de su PIB.',
          difficulty: 'hard',
        },
        {
          question: '¿Qué monumento es el más famoso de India?',
          options: ['Palacio de Mysore', 'Taj Mahal', 'Templo Dorado', 'Fuerte Rojo'],
          correctAnswer: 1,
          explanation: 'El Taj Mahal es el monumento más famoso de India, construido en el siglo XVII como mausoleo de amor.',
          difficulty: 'easy',
        },
        {
          question: '¿Cuál es la industria del cine más grande del mundo?',
          options: ['Hollywood', 'Bollywood', 'Nollywood', 'Cinema francés'],
          correctAnswer: 1,
          explanation: 'Bollywood (India) produce más de 1,800 películas al año, más que cualquier otra industria del cine.',
          difficulty: 'easy',
        },
        {
          question: '¿Cuántas lenguas se hablan en India?',
          options: ['50', '200', '700', '1,000'],
          correctAnswer: 2,
          explanation: 'En India se hablan más de 700 lenguas diferentes, reflejando su enorme diversidad cultural.',
          difficulty: 'medium',
        },
        {
          question: '¿Cuál es el destino principal de emigrantes indios?',
          options: ['Estados Unidos', 'Reino Unido', 'Emiratos Árabes Unidos', 'Canadá'],
          correctAnswer: 2,
          explanation: 'Emiratos Árabes Unidos es el principal destino de emigrantes indios, con más de 3.5 millones de trabajadores.',
          difficulty: 'medium',
        },
      ],
      rewards: { stars: 3, money: 200, experience: 160 },
    },
    {
      id: 'india_puzzle',
      type: 'puzzle',
      title: 'Taj Mahal',
      description: 'Arma el palacio del amor',
      difficulty: 'hard',
      imageUrl: 'taj_mahal.jpg',
      gridSize: 5,
      rewards: { stars: 3, money: 170, experience: 130 },
    },
    {
      id: 'india_memory',
      type: 'memory',
      title: 'Cultura India',
      description: 'Encuentra parejas',
      difficulty: 'medium',
      maxPairs: 16,
      pairs: [
        { id: 1, content: '🕉️' },
        { id: 2, content: '🏛️' },
        { id: 3, content: '🎭' },
        { id: 4, content: '🐘' },
        { id: 5, content: '🧘' },
        { id: 6, content: '🍛' },
        { id: 7, content: '🎬' },
        { id: 8, content: '🕌' },
        { id: 9, content: '🌶️' },
        { id: 10, content: '🎨' },
        { id: 11, content: '🪔' },
        { id: 12, content: '🐅' },
        { id: 13, content: '🏔️' },
        { id: 14, content: '🎪' },
        { id: 15, content: '🧘‍♀️' },
        { id: 16, content: '🎵' },
      ],
      rewards: { stars: 2, money: 150, experience: 110 },
    },
  ],
  requiredStats: {
    minMoney: 750,
    minHealth: 75,
    minMoral: 70,
    requiredDocuments: ['passport', 'visa'],
  },
  availablePortals: ['aereo'],
  unlockConditions: {
    previousCountries: ['turquia'],
    minStars: 86,
  },
};
