/**
 * México - País 4
 */

import { Country } from './types';

export const mexico: Country = {
  id: 'mexico',
  name: 'México',
  region: 'North America',
  flag: '🇲🇽',
  coordinates: { latitude: 23.6345, longitude: -102.5528 },
  description: 'País puente entre América Latina y Estados Unidos. Cultura milenaria.',
  culturalFacts: [
    'Civilizaciones mayas y aztecas',
    'Día de Muertos Patrimonio de la Humanidad',
    'Tacos, origen de comida mexicana',
    'Frida Kahlo y Diego Rivera',
  ],
  migrationContext: {
    reasons: ['País de tránsito masivo', 'Frontera con EE.UU.', 'Ruta de caravanas migrantes'],
    challenges: ['Violencia del crimen organizado', 'Detenciones migratorias', 'Muros y vigilancia'],
    destinations: ['Estados Unidos', 'Canadá', 'España'],
    statistics: { emigrants: '12 millones de mexicanos en EE.UU.', topDestination: 'Estados Unidos (97%)' },
  },
  activities: [
    {
      id: 'mexico_trivia',
      type: 'trivia',
      title: 'México Lindo',
      description: 'Conoce México',
      difficulty: 'easy',
      questions: [
        {
          question: '¿Qué civilizaciones antiguas vivieron en México?',
          options: ['Incas', 'Mayas y Aztecas', 'Vikingos', 'Romanos'],
          correctAnswer: 1,
          explanation: 'Los mayas y aztecas construyeron grandes ciudades en México, incluyendo Tenochtitlán y Chichén Itzá.',
          difficulty: 'easy',
        },
        {
          question: 'La capital de México, Ciudad de México, fue construida sobre las ruinas de:',
          options: ['Machu Picchu', 'Tenochtitlán', 'Tikal', 'Copán'],
          correctAnswer: 1,
          explanation: 'Tenochtitlán era la capital del imperio azteca. Los españoles la destruyeron y construyeron Ciudad de México sobre sus ruinas.',
          difficulty: 'medium',
        },
        {
          question: '¿Cuántos mexicanos aproximadamente viven en Estados Unidos?',
          options: ['5 millones', '12 millones', '20 millones', '30 millones'],
          correctAnswer: 1,
          explanation: 'Aproximadamente 12 millones de mexicanos viven en EE.UU., formando la comunidad latina más grande del país.',
          difficulty: 'medium',
        },
        {
          question: 'El Día de Muertos es una celebración mexicana que honra a:',
          options: ['Los dioses aztecas', 'Los difuntos y antepasados', 'La independencia', 'La cosecha'],
          correctAnswer: 1,
          explanation: 'El Día de Muertos (1-2 de noviembre) es una tradición prehispánica donde las familias recuerdan y honran a sus seres queridos fallecidos con ofrendas, flores de cempasúchil y calaveras de azúcar.',
          difficulty: 'medium',
        },
        {
          question: '¿Qué artista mexicana es famosa por sus autorretratos con cejas pobladas?',
          options: ['Diego Rivera', 'Frida Kahlo', 'Remedios Varo', 'María Izquierdo'],
          correctAnswer: 1,
          explanation: 'Frida Kahlo es una de las artistas más reconocidas del mundo. Sus autorretratos reflejan su vida, dolor físico y amor por la cultura mexicana.',
          difficulty: 'hard',
        },
        {
          question: 'México comparte su frontera norte con Estados Unidos, que tiene aproximadamente:',
          options: ['1,500 km', '2,000 km', '3,150 km', '4,000 km'],
          correctAnswer: 2,
          explanation: 'La frontera México-Estados Unidos mide aproximadamente 3,150 km. Es una de las fronteras más transitadas del mundo y también una de las más vigiladas.',
          difficulty: 'hard',
        },
      ],
      rewards: { stars: 3, money: 120, experience: 80 },
    },
    {
      id: 'mexico_puzzle',
      type: 'puzzle',
      title: 'Chichen Itzá',
      description: 'Arma la pirámide maya',
      difficulty: 'medium',
      imageUrl: 'chichen_itza.jpg',
      gridSize: 4,
      rewards: { stars: 2, money: 100, experience: 70 },
    },
    {
      id: 'mexico_memory',
      type: 'memory',
      title: 'Cultura Mexicana',
      description: 'Encuentra parejas',
      difficulty: 'easy',
      pairs: [
        { id: 1, content: '🌮' },
        { id: 2, content: '🏺' },
        { id: 3, content: '💀' },
        { id: 4, content: '🎺' },
        { id: 5, content: '🌶️' },
        { id: 6, content: '🦅' },
        { id: 7, content: '🎨' },
        { id: 8, content: '🌵' },
        { id: 9, content: '🏛️' },
        { id: 10, content: '🎭' },
        { id: 11, content: '🌺' },
        { id: 12, content: '🎉' },
        { id: 13, content: '🏖️' },
        { id: 14, content: '🎸' },
        { id: 15, content: '🦎' },
        { id: 16, content: '☀️' },
      ],
      maxPairs: 16,
      rewards: { stars: 2, money: 80, experience: 60 },
    },
  ],
  requiredStats: {
    minMoney: 300,
    minHealth: 65,
    minMoral: 55,
    requiredDocuments: ['passport'],
  },
  availablePortals: ['terrestre', 'aereo', 'clandestino'],
  unlockConditions: {
    previousCountries: ['panama'],
    minStars: 8,
  },
};
